const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
(async()=>{const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const f=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));fs.readFile(f,(err,data)=>{res.statusCode=err?404:200;res.end(err?'Not found':data)});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']}:{})});const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:'+server.address().port;
 await p.route('**/25_open.webp',r=>r.abort());await p.goto(url);await p.waitForFunction(()=>realImageStatus==='error');assert.equal(await p.locator('#status').innerText(),'CAPTURE UNAVAILABLE');assert.equal(await p.locator('#realTestImg').getAttribute('src'),null);
 await p.unroute('**/25_open.webp');await p.locator('#modeReal').click();await p.waitForFunction(()=>realImageStatus==='loaded');
 async function pick(t,i){await p.locator(`[data-picker="${t}"]`).click();await p.locator(`#sheetBody [data-idx="${i}"]`).click();}
 await p.route('**/l007/35_open.webp',async r=>{await new Promise(r=>setTimeout(r,1200));await r.continue()});await pick('focal',35);await pick('lens',21);await p.waitForFunction(()=>realImageStatus==='loaded');const expected=await p.locator('#realTestImg').getAttribute('src');await p.waitForTimeout(1400);assert.equal(await p.locator('#realTestImg').getAttribute('src'),expected);
 const unknown=await p.evaluate(()=>{const ci=DATA.cameras.findIndex(c=>!c.ronin4d&&c.formats.some(f=>!formatHasPhysicalDims(f)));return [ci,DATA.cameras[ci].formats.findIndex(f=>!formatHasPhysicalDims(f))]});await pick('camera',unknown[0]);await pick('format',unknown[1]);assert.equal(await p.locator('#area').innerText(),'—');assert.equal(await p.locator('#sensor').isVisible(),false);assert((await p.locator('#realInfo').innerText()).includes('not the selected camera frame'));
 await pick('camera',0);await pick('format',3);await pick('lens',7);await p.locator('#modeReal').click();await p.waitForFunction(()=>realImageStatus==='loaded');await p.waitForTimeout(250);
 for(const size of [{width:390,height:844},{width:844,height:390},{width:1280,height:900}]){await p.setViewportSize(size);await p.waitForTimeout(300);assert(await p.evaluate(()=>{const s=$('#sensor').getBoundingClientRect(),v=$('.viz').getBoundingClientRect();return s.width<=v.width+.1&&s.height<=v.height+.1}));}
 await p.reload();await p.waitForFunction(()=>realImageStatus==='loaded');await pick('camera',39);await p.locator('#modeOptical').click();await p.screenshot({path:path.resolve(__dirname,'desktop-large.png'),fullPage:true});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.resolve(__dirname,'recovery-results.json'),JSON.stringify({result:'PASS',tests:['HTTP missing image','retry','stale image response','unknown mode fallback label','known mode recovery','mobile portrait / landscape / desktop resize','reload'],pageErrors:errors},null,2));console.log('Recovery PASS');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
